// JsFromRoutes CacheKey 60a3dcb2ac6a277048dc500d4bdc53c5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as subjects } from './SubjectsApi'
export { default as authors } from './AuthorsApi'
export { default as papers } from './PapersApi'
