// JsFromRoutes CacheKey da3de625934dbee2c6d97ee5054b54da
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as sessions } from './SessionsApi'
export { default as subjects } from './SubjectsApi'
export { default as users } from './UsersApi'
export { default as tags } from './TagsApi'
export { default as authors } from './AuthorsApi'
export { default as papers } from './PapersApi'
