// JsFromRoutes CacheKey a5b3b77c5569d3726e5238693aa1d35c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as sessions } from './SessionsApi'
export { default as subjects } from './SubjectsApi'
export { default as users } from './UsersApi'
export { default as recommendations } from './RecommendationsApi'
export { default as tags } from './TagsApi'
export { default as authors } from './AuthorsApi'
export { default as papers } from './PapersApi'
