// JsFromRoutes CacheKey e86b5c3cbe27c919418ea2b767892925
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/authors'),
  show: /* #__PURE__ */ definePathHelper('get', '/authors/:id'),
}
