// JsFromRoutes CacheKey 678c3ac29ed366cce9b10c18c0fc912d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/authors/:id'),
}
