// JsFromRoutes CacheKey 8b9db05a5ad59486fcb288391a4afcd8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/authors'),
  create: /* #__PURE__ */ definePathHelper('post', '/authors'),
  new: /* #__PURE__ */ definePathHelper('get', '/authors/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/authors/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/authors/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/authors/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/authors/:id'),
}
