// JsFromRoutes CacheKey 6f2920f800f292018c08410e76f44680
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/papers/:id'),
}
