// JsFromRoutes CacheKey e0b1134f67e80241c0822b8e42faf066
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/papers'),
  show: /* #__PURE__ */ definePathHelper('get', '/papers/:id'),
}
