// JsFromRoutes CacheKey e2e47970fb7e1d5750298df07966401c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/papers'),
  create: /* #__PURE__ */ definePathHelper('post', '/papers'),
  new: /* #__PURE__ */ definePathHelper('get', '/papers/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/papers/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/papers/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/papers/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/papers/:id'),
}
