// JsFromRoutes CacheKey 80c3fba810eff2492699de9dea8d0b2a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/recommendations'),
  create: /* #__PURE__ */ definePathHelper('post', '/recommendations'),
}
