// JsFromRoutes CacheKey 66c7ceee5a09f26876575b50e40749ec
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  omni: /* #__PURE__ */ definePathHelper('get', '/auth/:provider/callback'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/session'),
  create: /* #__PURE__ */ definePathHelper('post', '/session'),
}
