// JsFromRoutes CacheKey f2d5c4650aef6d071c327d295b9d5153
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  destroy: /* #__PURE__ */ definePathHelper('delete', '/session'),
  create: /* #__PURE__ */ definePathHelper('post', '/session'),
}
