// JsFromRoutes CacheKey b0bb8ff7d8dfd304f22ade2406429b2e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/subjects'),
  create: definePathHelper('post', '/subjects'),
  new: definePathHelper('get', '/subjects/new'),
  edit: definePathHelper('get', '/subjects/:id/edit'),
  get: definePathHelper('get', '/subjects/:id'),
  update: definePathHelper('patch', '/subjects/:id'),
  destroy: definePathHelper('delete', '/subjects/:id'),
}
