// JsFromRoutes CacheKey ce6885185ee2292b78b27af7aa26e066
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/subjects'),
  create: /* #__PURE__ */ definePathHelper('post', '/subjects'),
  new: /* #__PURE__ */ definePathHelper('get', '/subjects/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/subjects/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/subjects/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/subjects/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/subjects/:id'),
}
