// JsFromRoutes CacheKey be43ba7daab0498fc74cc989ce714be8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/subjects/:id'),
}
