// JsFromRoutes CacheKey dca0f6496993b270a87ed6766cffce6d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/tags'),
  show: /* #__PURE__ */ definePathHelper('get', '/tags/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/tags/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/tags/:id'),
}
