// JsFromRoutes CacheKey 5713168d4f99061f7b25e7f4a0f13838
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/users'),
}
