// JsFromRoutes CacheKey b43e8108f07e0b8f289aef307c49578c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/users'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:id'),
}
