// JsFromRoutes CacheKey a847d0a98c562ab551cb78ffe99d7bac
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/users'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:id'),
}
