# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Subject.create(arxiv: 'astro-ph', title: 'Astrophysics')
Subject.create(arxiv: 'cond-mat', title: 'Condensed Matter')
Subject.create(arxiv: 'cs', title: 'Computer Science')
Subject.create(arxiv: 'econ', title: 'Economics')
Subject.create(arxiv: 'eess',
               title: 'Electric Engineering and Systems Science')
Subject.create(arxiv: 'math', title: 'Mathematics')
Subject.create(arxiv: 'nlin', title: 'Nonlinear Sciences')
Subject.create(arxiv: 'physics', title: 'Physics')
Subject.create(arxiv: 'q-bio', title: 'Quantitative Biology')
Subject.create(arxiv: 'q-fin', title: 'Quantitative Finance')
Subject.create(arxiv: 'stat', title: 'Statistics')

Category.create(arxiv: 'astro-ph', title: 'Astrophysics')
Category.create(arxiv: 'astro-ph.CO', title: 'Cosmology and Nongalactic Astrophysics')
Category.create(arxiv: 'astro-ph.EP', title: 'Earth and Planetary Astrophysics')
Category.create(arxiv: 'astro-ph.GA', title: 'Astrophysics of Galaxies')
Category.create(arxiv: 'astro-ph.HE', title: 'High Energy Astrophysical Phenomena')
Category.create(arxiv: 'astro-ph.IM', title: 'Instrumentation and Methods for Astrophysics')
Category.create(arxiv: 'astro-ph.SR', title: 'Solar and Stellar Astrophysics')
Category.create(arxiv: 'cond-mat.dis-nn', title: 'Disordered Systems and Neural Networks')
Category.create(arxiv: 'cond-mat.mes-hall', title: 'Mesoscale and Nanoscale Physics')
Category.create(arxiv: 'cond-mat.mtrl-sci', title: 'Materials Science')
Category.create(arxiv: 'cond-mat.other', title: 'Other Condensed Matter')
Category.create(arxiv: 'cond-mat.quant-gas', title: 'Quantum Gases')
Category.create(arxiv: 'cond-mat.soft', title: 'Soft Condensed Matter')
Category.create(arxiv: 'cond-mat.stat-mech', title: 'Statistical Mechanics')
Category.create(arxiv: 'cond-mat.str-el', title: 'Strongly Correlated Electrons')
Category.create(arxiv: 'cond-mat.supr-con', title: 'Superconductivity')
Category.create(arxiv: 'cs.AI', title: 'Artificial Intelligence')
Category.create(arxiv: 'cs.AR', title: 'Hardware Architecture')
Category.create(arxiv: 'cs.CC', title: 'Computational Complexity')
Category.create(arxiv: 'cs.CE', title: 'Computational Engineering, Finance, and Science')
Category.create(arxiv: 'cs.CG', title: 'Computational Geometry')
Category.create(arxiv: 'cs.CL', title: 'Computation and Language')
Category.create(arxiv: 'cs.CR', title: 'Cryptography and Security')
Category.create(arxiv: 'cs.CV', title: 'Computer Vision and Pattern Recognition')
Category.create(arxiv: 'cs.CY', title: 'Computers and Society')
Category.create(arxiv: 'cs.DB', title: 'Databases')
Category.create(arxiv: 'cs.DC', title: 'Distributed, Parallel, and Cluster Computing')
Category.create(arxiv: 'cs.DL', title: 'Digital Libraries')
Category.create(arxiv: 'cs.DM', title: 'Discrete Mathematics')
Category.create(arxiv: 'cs.DS', title: 'Data Structures and Algorithms')
Category.create(arxiv: 'cs.ET', title: 'Emerging Technologies')
Category.create(arxiv: 'cs.FL', title: 'Formal Languages and Automata Theory')
Category.create(arxiv: 'cs.GL', title: 'General Literature')
Category.create(arxiv: 'cs.GR', title: 'Graphics')
Category.create(arxiv: 'cs.GT', title: 'Computer Science and Game Theory')
Category.create(arxiv: 'cs.HC', title: 'Human-Computer Interaction')
Category.create(arxiv: 'cs.IR', title: 'Information Retrieval')
Category.create(arxiv: 'cs.IT', title: 'Information Theory')
Category.create(arxiv: 'cs.LG', title: 'Learning')
Category.create(arxiv: 'cs.LO', title: 'Logic in Computer Science')
Category.create(arxiv: 'cs.MA', title: 'Multiagent Systems')
Category.create(arxiv: 'cs.MM', title: 'Multimedia')
Category.create(arxiv: 'cs.MS', title: 'Mathematical Software')
Category.create(arxiv: 'cs.NA', title: 'Numerical Analysis')
Category.create(arxiv: 'cs.NE', title: 'Neural and Evolutionary Computing')
Category.create(arxiv: 'cs.NI', title: 'Networking and Internet Architecture')
Category.create(arxiv: 'cs.OH', title: 'Other Computer Science')
Category.create(arxiv: 'cs.OS', title: 'Operating Systems')
Category.create(arxiv: 'cs.PF', title: 'Performance')
Category.create(arxiv: 'cs.PL', title: 'Programming Languages')
Category.create(arxiv: 'cs.RO', title: 'Robotics')
Category.create(arxiv: 'cs.SC', title: 'Symbolic Computation')
Category.create(arxiv: 'cs.SD', title: 'Sound')
Category.create(arxiv: 'cs.SE', title: 'Software Engineering')
Category.create(arxiv: 'cs.SI', title: 'Social and Information Networks')
Category.create(arxiv: 'cs.SY', title: 'Systems and Control')
Category.create(arxiv: 'econ.EM', title: 'Econometrics')
Category.create(arxiv: 'eess.AS', title: 'Audio and Speech Processing')
Category.create(arxiv: 'eess.IV', title: 'Image and Video Processing')
Category.create(arxiv: 'eess.SP', title: 'Signal Processing')
Category.create(arxiv: 'gr-qc', title: 'General Relativity and Quantum Cosmology')
Category.create(arxiv: 'hep-ex', title: 'High Energy Physics - Experiment')
Category.create(arxiv: 'hep-lat', title: 'High Energy Physics - Lattice')
Category.create(arxiv: 'hep-ph', title: 'High Energy Physics - Phenomenology')
Category.create(arxiv: 'hep-th', title: 'High Energy Physics - Theory')
Category.create(arxiv: 'math.AC', title: 'Commutative Algebra')
Category.create(arxiv: 'math.AG', title: 'Algebraic Geometry')
Category.create(arxiv: 'math.AP', title: 'Analysis of PDEs')
Category.create(arxiv: 'math.AT', title: 'Algebraic Topology')
Category.create(arxiv: 'math.CA', title: 'Classical Analysis and ODEs')
Category.create(arxiv: 'math.CO', title: 'Combinatorics')
Category.create(arxiv: 'math.CT', title: 'Category Theory')
Category.create(arxiv: 'math.CV', title: 'Complex Variables')
Category.create(arxiv: 'math.DG', title: 'Differential Geometry')
Category.create(arxiv: 'math.DS', title: 'Dynamical Systems')
Category.create(arxiv: 'math.FA', title: 'Functional Analysis')
Category.create(arxiv: 'math.GM', title: 'General Mathematics')
Category.create(arxiv: 'math.GN', title: 'General Topology')
Category.create(arxiv: 'math.GR', title: 'Group Theory')
Category.create(arxiv: 'math.GT', title: 'Geometric Topology')
Category.create(arxiv: 'math.HO', title: 'History and Overview')
Category.create(arxiv: 'math.IT', title: 'Information Theory')
Category.create(arxiv: 'math.KT', title: 'K-Theory and Homology')
Category.create(arxiv: 'math.LO', title: 'Logic')
Category.create(arxiv: 'math.MG', title: 'Metric Geometry')
Category.create(arxiv: 'math.MP', title: 'Mathematical Physics')
Category.create(arxiv: 'math.NA', title: 'Numerical Analysis')
Category.create(arxiv: 'math.NT', title: 'Number Theory')
Category.create(arxiv: 'math.OA', title: 'Operator Algebras')
Category.create(arxiv: 'math.OC', title: 'Optimization and Control')
Category.create(arxiv: 'math.PR', title: 'Probability')
Category.create(arxiv: 'math.QA', title: 'Quantum Algebra')
Category.create(arxiv: 'math.RA', title: 'Rings and Algebras')
Category.create(arxiv: 'math.RT', title: 'Representation Theory')
Category.create(arxiv: 'math.SG', title: 'Symplectic Geometry')
Category.create(arxiv: 'math.SP', title: 'Spectral Theory')
Category.create(arxiv: 'math.ST', title: 'Statistics Theory')
Category.create(arxiv: 'math-ph', title: 'Mathematical Physics')
Category.create(arxiv: 'nlin.AO', title: 'Adaptation and Self-Organizing Systems')
Category.create(arxiv: 'nlin.CD', title: 'Chaotic Dynamics')
Category.create(arxiv: 'nlin.CG', title: 'Cellular Automata and Lattice Gases')
Category.create(arxiv: 'nlin.PS', title: 'Pattern Formation and Solitons')
Category.create(arxiv: 'nlin.SI', title: 'Exactly Solvable and Integrable Systems')
Category.create(arxiv: 'nucl-ex', title: 'Nuclear Experiment')
Category.create(arxiv: 'nucl-th', title: 'Nuclear Theory')
Category.create(arxiv: 'physics.acc-ph', title: 'Accelerator Physics')
Category.create(arxiv: 'physics.ao-ph', title: 'Atmospheric and Oceanic Physics')
Category.create(arxiv: 'physics.app-ph', title: 'Applied Physics')
Category.create(arxiv: 'physics.atm-clus', title: 'Atomic and Molecular Clusters')
Category.create(arxiv: 'physics.atom-ph', title: 'Atomic Physics')
Category.create(arxiv: 'physics.bio-ph', title: 'Biological Physics')
Category.create(arxiv: 'physics.chem-ph', title: 'Chemical Physics')
Category.create(arxiv: 'physics.class-ph', title: 'Classical Physics')
Category.create(arxiv: 'physics.comp-ph', title: 'Computational Physics')
Category.create(arxiv: 'physics.data-an', title: 'Data Analysis, Statistics and Probability')
Category.create(arxiv: 'physics.ed-ph', title: 'Physics Education')
Category.create(arxiv: 'physics.flu-dyn', title: 'Fluid Dynamics')
Category.create(arxiv: 'physics.gen-ph', title: 'General Physics')
Category.create(arxiv: 'physics.geo-ph', title: 'Geophysics')
Category.create(arxiv: 'physics.hist-ph', title: 'History and Philosophy of Physics')
Category.create(arxiv: 'physics.ins-det', title: 'Instrumentation and Detectors')
Category.create(arxiv: 'physics.med-ph', title: 'Medical Physics')
Category.create(arxiv: 'physics.optics', title: 'Optics')
Category.create(arxiv: 'physics.plasm-ph', title: 'Plasma Physics')
Category.create(arxiv: 'physics.pop-ph', title: 'Popular Physics')
Category.create(arxiv: 'physics.soc-ph', title: 'Physics and Society')
Category.create(arxiv: 'physics.space-ph', title: 'Space Physics')
Category.create(arxiv: 'q-bio.BM', title: 'Biomolecules')
Category.create(arxiv: 'q-bio.CB', title: 'Cell Behavior')
Category.create(arxiv: 'q-bio.GN', title: 'Genomics')
Category.create(arxiv: 'q-bio.MN', title: 'Molecular Networks')
Category.create(arxiv: 'q-bio.NC', title: 'Neurons and Cognition')
Category.create(arxiv: 'q-bio.OT', title: 'Other Quantitative Biology')
Category.create(arxiv: 'q-bio.PE', title: 'Populations and Evolution')
Category.create(arxiv: 'q-bio.QM', title: 'Quantitative Methods')
Category.create(arxiv: 'q-bio.SC', title: 'Subcellular Processes')
Category.create(arxiv: 'q-bio.TO', title: 'Tissues and Organs')
Category.create(arxiv: 'q-fin.CP', title: 'Computational Finance')
Category.create(arxiv: 'q-fin.EC', title: 'Economics')
Category.create(arxiv: 'q-fin.GN', title: 'General Finance')
Category.create(arxiv: 'q-fin.MF', title: 'Mathematical Finance')
Category.create(arxiv: 'q-fin.PM', title: 'Portfolio Management')
Category.create(arxiv: 'q-fin.PR', title: 'Pricing of Securities')
Category.create(arxiv: 'q-fin.RM', title: 'Risk Management')
Category.create(arxiv: 'q-fin.ST', title: 'Statistical Finance')
Category.create(arxiv: 'q-fin.TR', title: 'Trading and Market Microstructure')
Category.create(arxiv: 'quant-ph', title: 'Quantum Physics')
Category.create(arxiv: 'stat.AP', title: 'Applications')
Category.create(arxiv: 'stat.CO', title: 'Computation')
Category.create(arxiv: 'stat.ME', title: 'Methodology')
Category.create(arxiv: 'stat.ML', title: 'Machine Learning')
Category.create(arxiv: 'stat.OT', title: 'Other Statistics')
Category.create(arxiv: 'stat.TH', title: 'Statistics Theory')
